AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-zen

  Sample SAM Template for sam-zen
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  CustomDomain:
    Description: The Custom Domain linked to this Stack
    Type: String
    Default: api.coderdojokinsale.com
Resources:
  ZenAwardsApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: awards/template.yaml
  ZenBadgesApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: badges/template.yaml
  ZenBeltsApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: belts/template.yaml
  ZenDojosApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: dojos/template.yaml
  ZenEventsApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: events/template.yaml




